### PR TITLE
Create template for Integrations Directory application

### PR DESCRIPTION
**Pull request by tacoapp**

### CODE REVIEW

**Comment by gjtorikian** [comment]
Please email us at `partnerships@github.com` if you'd like to discuss the integrations directory.

**Comment by troy** [comment]
@gjtorikian: I have an email thread going with @joewadcan, who is reviewing a draft of my own integration directory application. I saw the request for contributions on https://developer.github.com/:

> This website is a public GitHub repository. Please help us by forking the project and adding to it

.. and figured I'd try to save other integrators the time it took me :)

It's certainly your prerogative to give contributors the brush-off without explaining why[1]. Aside from GitHub's purpose and the contribution solicitation above, the template seems useful because it's what https://developer.github.com/integrations-directory/getting-listed/ told me to create :-) Turning "Send us this stuff, preferably in Markdown" into the equivalent Markdown doesn't seem like a speculative change.

[1]: As in "This format is wrong because.." or even "We don't want a template. Applicants should need to jump through this extra hoop, even if it takes them the same amount of time it took you"

**Comment by troy** [comment]
BTW, I'm totally willing to put in more time to change or otherwise improve this if that's what it needs. I'm going to end up with a completed template anyway just as a byproduct of my own application, and if I can put in a bit more of my time to save time for future integration directory applicants, I'm willing.

**Comment by mikemcquaid** [comment]
I'll let @joewadcan and/or @kdaigle chip in here with thoughts.

**Comment by joewadcan** [comment]
> Aside from GitHub's purpose and the contribution solicitation above, the template seems useful because it's what https://developer.github.com/integrations-directory/getting-listed/ told me to create :-) Turning "Send us this stuff, preferably in Markdown" into the equivalent Markdown doesn't seem like a speculative change.

> if I can put in a bit more of my time to save time for future integration directory applicants, I'm willing.

Hey @troy ! Really appreciate the PR on developer.github.com - contributions for improvement are a big reason why we open source things like this to begin with! The change you're proposing is something we definitely tried out (our flow is naturally repository based), but decided against it for the time being. 

The biggest issue we saw was that the folks who are often filling out this information aren't comfortable in the GitHub flow (it may well be a Marketing person sending us the content who doesn't have a :octocat: account). The other reason is that the Directory is still new (5 months old), and so we're iterating quite a bit on the content, required links, and media for each listing. With the listing detail changing and the friction that folks had learning GitHub, we opted to just use plain email for now. 

I'm pretty sure we'll end up with a repo-based process (since it's pretty hard for us to manually make all the updates needed for each listing), but for now doing all the :muscle: helps us define the process itself. Thanks again for the contribution :smiley_cat: !

**Comment by troy** [comment]
Sounds good, and thanks for reading and considering the PR :+1:

**Pull request closed without merging**
