### PR TITLE
changed IssuesEvent to IssueEvent for consistency

### PR DESCRIPTION
**Pull request by mickaelandrieu**

### CODE REVIEW

**Comment by izuzak** [comment]
Thanks for opening a PR, but `IssuesEvent` is actually the name of the event as you would see it in the payload of the events API, not `IssueEvent`. Can you clarify in what way this would improve consistency?

**Comment by mickaelandrieu** [comment]
the event dispatched is related to one and only one issue.

**Comment by izuzak** [comment]
> the event dispatched is related to one and only one issue.

Thanks for clarifying. While that's true and if I could pick the name for that event today I would pick `IssueEvent`, the name `IssuesEvent` is what's actually used in the payload, so changing that would be more confusing. And changing the name in the payload isn't an option since it would be considered a breaking change.

**Comment by lovrerada** [comment]
Hshdhdujwhsbsilxjfo

**Comment by mickaelandrieu** [comment]
@izuzak thank you for answer.  You can close ;)

**Comment by lovrerada** [comment]
Sent from Huawei MediaPad

Mickaël Andrieu <notifications@github.com> je napisao:

**Pull request closed without merging**
