### PR TITLE
incorrect key for commit head

### PR DESCRIPTION
**Pull request by stevepeak**
Let me know if an example is necessary. Thanks!

``` json
{
  "after": "6b3d35683e4358345bc42981e0105e8ecf398b62", 
  "base_ref": null, 
  "before": "58ac6bd52c6af71d5b77fda4d3a8d59fa70e103d", 
  "commits": [...
```

> No "head" key found in the body.

### CODE REVIEW

**Comment by davidcelis** [comment]
> Let me know if an example is necessary.

Not at all necessary 😄 I can see in some of our own `PushEvent` payloads that you definitely caught a mistake. Thank you, @stevepeak!

**Comment by Shredder121** [comment]
This is a recurring issue right?
It's already documented, or am I missing something?
[`head` should be `after` in PushEvent #966](https://github.com/github/developer.github.com/pull/966)

**Comment by davidcelis** [comment]
You're right, I mistook which payload was being edited. Thanks for the catch, @Shredder121.

**Comment by davidcelis** [comment]
@stevepeak Sorry for the confusion, I've reverted this PR. The PushEvent payload in the API and the webhook payload don't match. This is unfortunately confusing, but has to remain true for backwards compatibility. There's a note that denotes this in [the docs](https://developer.github.com/v3/activity/events/types/#pushevent):

> The Events API PushEvent payload is described in the table below. The example payload below that is from a webhook delivery and will differ from the Events API PushEvent payload.

**Comment by stevepeak** [comment]
No worries :) Thank you!

**Pull request merged**
