### PR TITLE
No pagination done when listing forks

### PR DESCRIPTION
**Pull request by JanX2**

### CODE REVIEW

**Comment by gjtorikian** [comment]
I just checked this and see the pagination header:

```
curl -ni https://api.github.com/repos/twbs/bootstrap/forks
HTTP/1.1 200 OK
Link: <https://api.github.com/repositories/2126244/forks?page=2>; rel="next", <https://api.github.com/repositories/2126244/forks?page=1258>; rel="last"
```

Could you share a `curl` call where this is not working?

**Comment by JanX2** [comment]
This is what I get as a non-authenticated user instead:

```
HTTP/1.1 200 OK
Server: GitHub.com
Date: Sun, 14 Feb 2016 10:42:19 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 161861
Status: 200 OK
X-RateLimit-Limit: 60
X-RateLimit-Remaining: 59
X-RateLimit-Reset: 1455450139
Cache-Control: public, max-age=60, s-maxage=60
ETag: "f57ccd585f9cc242e7647f461535b83e"
Vary: Accept
X-GitHub-Media-Type: github.v3
Link: <https://api.github.com/repositories/2126244/forks?page=2>; rel="next", <https://api.github.com/repositories/2126244/forks?page=1258>; rel="last"
Access-Control-Allow-Credentials: true
Access-Control-Expose-Headers: ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval
Access-Control-Allow-Origin: *
Content-Security-Policy: default-src 'none'
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Content-Type-Options: no sniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
Vary: Accept-Encoding
X-Served-By: 76d9828c7e4f1d910f7ba069e90ce976
X-GitHub-Request-Id: 5B592094:A4EB:1395BF93:56C05A0A

```

**Comment by JanX2** [comment]
This is what I get on another repo:

`curl -si https://api.github.com/repos/octiplex/OEXTokenField/forks`

```
HTTP/1.1 200 OK
Server: GitHub.com
Date: Sun, 14 Feb 2016 10:44:32 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 54406
Status: 200 OK
X-RateLimit-Limit: 60
X-RateLimit-Remaining: 58
X-RateLimit-Reset: 1455450139
Cache-Control: public, max-age=60, s-maxage=60
ETag: "42c66bf2794c1b83e49beb32fac781ad"
Vary: Accept
X-GitHub-Media-Type: github.v3
Access-Control-Allow-Credentials: true
Access-Control-Expose-Headers: ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval
Access-Control-Allow-Origin: *
Content-Security-Policy: default-src 'none'
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Content-Type-Options: no sniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
Vary: Accept-Encoding
X-Served-By: 065b43cd9674091fec48a221b420fbb3
X-GitHub-Request-Id: 5B592094:1601B:350FFB2:56C05A8F

```

**Comment by Shredder121** [comment]
[You seem to only have 11 forks, which fits in the defaul page size of 30](https://github.com/octiplex/OEXTokenField/network/members).

If you try a smaller page size you can see the `Link`:
`curl -ni https://api.github.com/repos/octiplex/OEXTokenField/forks?per_page=2`

```
HTTP/1.1 200 OK
Server: GitHub.com
Date: Sun, 14 Feb 2016 10:55:24 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 10672
Status: 200 OK
X-RateLimit-Limit: 60
X-RateLimit-Remaining: 55
X-RateLimit-Reset: 1455450752
Cache-Control: public, max-age=60, s-maxage=60
ETag: "8c7c2ce2d016f539322359db82308376"
Vary: Accept
X-GitHub-Media-Type: github.v3
Link: <https://api.github.com/repositories/8908017/forks?per_page=2&page=2>; rel="next", <https://api.github.com/repositories/8908017/forks?per_page=2&page=5>; rel="last"
Access-Control-Allow-Credentials: true
Access-Control-Expose-Headers: ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval
Access-Control-Allow-Origin: *
Content-Security-Policy: default-src 'none'
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
Vary: Accept-Encoding
X-Served-By: b0ef53392caa42315c6206737946d931
X-GitHub-Request-Id: 55964F0B:14593:CCA81DA:56C05D1C
```

**Comment by JanX2** [comment]
So I need two code paths? One for pages, one without? Could I set `per_page` arbitrarily high?

**Comment by Shredder121** [comment]
You can't set `per_page` arbitrarily high, so code to walk over the pages is necessary.
GitHub doesn't accept a `per_page` higher than 100 to prevent calls from hogging resources (this is then solved per user with rate limits).

What I can suggest is copying all the user/repo names on the [Network Members][] tab.
After that, all the data is local, so you don't have to hit the API.
```
@octiplex octiplex / OEXTokenField
  @alanjrogers alanjrogers / OEXTokenField
  @aufflick aufflick / OEXTokenField
    @MichaelLeach MichaelLeach / OEXTokenField
  @danielalcanja danielalcanja / OEXTokenField
  @DrummerB DrummerB / OEXTokenField
  @gloubibou gloubibou / OEXTokenField
  @JanX2 JanX2 / OEXTokenField
  @Producteev Producteev / OEXTokenField
  @renfeisong renfeisong / OEXTokenField
  @tbmvp tbmvp / OEXTokenField
  @veronica41 veronica41 / OEXTokenField
```

Remove all occurences of `^\s*@\S+ `(with a trailing space).

```
octiplex / OEXTokenField
alanjrogers / OEXTokenField
aufflick / OEXTokenField
MichaelLeach / OEXTokenField
danielalcanja / OEXTokenField
DrummerB / OEXTokenField
gloubibou / OEXTokenField
JanX2 / OEXTokenField
Producteev / OEXTokenField
renfeisong / OEXTokenField
tbmvp / OEXTokenField
veronica41 / OEXTokenField
```
Save this as `forks.txt`, these pairs are going to be used to add the remotes.

You can use a little `sed` to add the remotes, like this:

`sed -r 's_(\S+) / (\S+)_\1 \\"git@github.com:\1/\2.git\\"_' forks.txt | xargs -t -n2 git remote add`.

It's not flawless, since at 1000+ forks the list is truncated I think, but not everyone is so lucky to have that many forks. (Besides, usually with so many forks there __is__ one repo where it's at).

Hope it is of some help!


[Network Members]: https://github.com/octiplex/OEXTokenField/network/members

**Comment by Shredder121** [comment]
__NOTE: I updated the `sed` command, too many escapes of the `"`, sorry__

**Comment by Shredder121** [comment]
I did some research, it seems that Mac's `sed` is [different enough to warrant an extra clause](http://unix.stackexchange.com/questions/13711/differences-between-sed-on-mac-osx-and-other-standard-sed/131940#131940).

For Mac (untested):
`sed -E 's_(\S+) / (\S+)_\1 "git@github.com:\1/\2.git"_' forks.txt | xargs -t -n2 git remote add`.

**Comment by JanX2** [comment]
Thanks! Why have I always overlooked the Network Members tab?! 

Any chance to get API access to the Network Members?

**Comment by gjtorikian** [comment]
The Network Members *is* the same as https://developer.github.com/v3/repos/forks/#list-forks. 

I suggest reading up on [Traversing with Pagination](https://developer.github.com/guides/traversing-with-pagination/). You don't need two code paths depending on the quantity of the forks. You can write a script to properly iterate over the pages, if any. 

As the original issue was resolved, I'm closing this out.

**Pull request closed without merging**
