### PR TITLE
Add "Shell" section to Octokit client libs; add link to ok.sh

### PR DESCRIPTION
**Pull request by whiteinge**

### CODE REVIEW

**Comment by izuzak** [comment]
This is amazing, @whiteinge :zap: -- thanks for creating this and submitting this pull request!

The Octokit name is being used to represent officially supported libraries, so adding this library to the list could mislead users into thinking that it's a project by GitHub. Would you mind changing the name to something other than Octokit? (See https://github.com/github/developer.github.com/pull/671 for a similar discussion.)

**Comment by whiteinge** [comment]
No problem. I'll puzzle over a replacement name and ping you back in the morning.

**Comment by whiteinge** [comment]
Project has been renamed.

**Comment by izuzak** [comment]
:sparkling_heart: Thanks again! Looking forward to trying this out

**Pull request merged**
