### PR TITLE
Sync changes from upstream repository

### PR DESCRIPTION
**Pull request by hubot**
### Added files: 

* .bowerrc
* assets/vendor/octicons/.bower.json
* assets/vendor/octicons/CHANGELOG.md
* assets/vendor/octicons/CONTRIBUTING.md
* assets/vendor/octicons/README.md
* assets/vendor/octicons/bower.json
* assets/vendor/octicons/octicons/README.md
* assets/vendor/octicons/octicons/octicons-local.ttf
* assets/vendor/octicons/octicons/octicons.eot
* assets/vendor/octicons/octicons/octicons.less
* assets/vendor/octicons/octicons/octicons.scss
* assets/vendor/octicons/octicons/octicons.svg
* assets/vendor/octicons/octicons/octicons.ttf
* assets/vendor/octicons/octicons/octicons.woff
* assets/vendor/octicons/octicons/sprockets-octicons.scss
* assets/vendor/octicons/package.json
* assets/vendor/octicons/svg/alert.svg
* assets/vendor/octicons/svg/arrow-down.svg
* assets/vendor/octicons/svg/arrow-left.svg
* assets/vendor/octicons/svg/arrow-right.svg
* assets/vendor/octicons/svg/arrow-small-down.svg
* assets/vendor/octicons/svg/arrow-small-left.svg
* assets/vendor/octicons/svg/arrow-small-right.svg
* assets/vendor/octicons/svg/arrow-small-up.svg
* assets/vendor/octicons/svg/arrow-up.svg
* assets/vendor/octicons/svg/beaker.svg
* assets/vendor/octicons/svg/bell.svg
* assets/vendor/octicons/svg/book.svg
* assets/vendor/octicons/svg/bookmark.svg
* assets/vendor/octicons/svg/briefcase.svg
* assets/vendor/octicons/svg/broadcast.svg
* assets/vendor/octicons/svg/browser.svg
* assets/vendor/octicons/svg/bug.svg
* assets/vendor/octicons/svg/calendar.svg
* assets/vendor/octicons/svg/check.svg
* assets/vendor/octicons/svg/checklist.svg
* assets/vendor/octicons/svg/chevron-down.svg
* assets/vendor/octicons/svg/chevron-left.svg
* assets/vendor/octicons/svg/chevron-right.svg
* assets/vendor/octicons/svg/chevron-up.svg
* assets/vendor/octicons/svg/circle-slash.svg
* assets/vendor/octicons/svg/circuit-board.svg
* assets/vendor/octicons/svg/clippy.svg
* assets/vendor/octicons/svg/clock.svg
* assets/vendor/octicons/svg/cloud-download.svg
* assets/vendor/octicons/svg/cloud-upload.svg
* assets/vendor/octicons/svg/code.svg
* assets/vendor/octicons/svg/color-mode.svg
* assets/vendor/octicons/svg/comment-discussion.svg
* assets/vendor/octicons/svg/comment.svg
* assets/vendor/octicons/svg/credit-card.svg
* assets/vendor/octicons/svg/dash.svg
* assets/vendor/octicons/svg/dashboard.svg
* assets/vendor/octicons/svg/database.svg
* assets/vendor/octicons/svg/desktop-download.svg
* assets/vendor/octicons/svg/device-camera-video.svg
* assets/vendor/octicons/svg/device-camera.svg
* assets/vendor/octicons/svg/device-desktop.svg
* assets/vendor/octicons/svg/device-mobile.svg
* assets/vendor/octicons/svg/diff-added.svg
* assets/vendor/octicons/svg/diff-ignored.svg
* assets/vendor/octicons/svg/diff-modified.svg
* assets/vendor/octicons/svg/diff-removed.svg
* assets/vendor/octicons/svg/diff-renamed.svg
* assets/vendor/octicons/svg/diff.svg
* assets/vendor/octicons/svg/ellipsis.svg
* assets/vendor/octicons/svg/eye.svg
* assets/vendor/octicons/svg/file-binary.svg
* assets/vendor/octicons/svg/file-code.svg
* assets/vendor/octicons/svg/file-directory.svg
* assets/vendor/octicons/svg/file-media.svg
* assets/vendor/octicons/svg/file-pdf.svg
* assets/vendor/octicons/svg/file-submodule.svg
* assets/vendor/octicons/svg/file-symlink-directory.svg
* assets/vendor/octicons/svg/file-symlink-file.svg
* assets/vendor/octicons/svg/file-text.svg
* assets/vendor/octicons/svg/file-zip.svg
* assets/vendor/octicons/svg/flame.svg
* assets/vendor/octicons/svg/fold.svg
* assets/vendor/octicons/svg/gear.svg
* assets/vendor/octicons/svg/gift.svg
* assets/vendor/octicons/svg/gist-secret.svg
* assets/vendor/octicons/svg/gist.svg
* assets/vendor/octicons/svg/git-branch.svg
* assets/vendor/octicons/svg/git-commit.svg
* assets/vendor/octicons/svg/git-compare.svg
* assets/vendor/octicons/svg/git-merge.svg
* assets/vendor/octicons/svg/git-pull-request.svg
* assets/vendor/octicons/svg/globe.svg
* assets/vendor/octicons/svg/graph.svg
* assets/vendor/octicons/svg/heart.svg
* assets/vendor/octicons/svg/history.svg
* assets/vendor/octicons/svg/home.svg
* assets/vendor/octicons/svg/horizontal-rule.svg
* assets/vendor/octicons/svg/hubot.svg
* assets/vendor/octicons/svg/inbox.svg
* assets/vendor/octicons/svg/info.svg
* assets/vendor/octicons/svg/issue-closed.svg
* assets/vendor/octicons/svg/issue-opened.svg
* assets/vendor/octicons/svg/issue-reopened.svg
* assets/vendor/octicons/svg/jersey.svg
* assets/vendor/octicons/svg/key.svg
* assets/vendor/octicons/svg/keyboard.svg
* assets/vendor/octicons/svg/law.svg
* assets/vendor/octicons/svg/light-bulb.svg
* assets/vendor/octicons/svg/link-external.svg
* assets/vendor/octicons/svg/link.svg
* assets/vendor/octicons/svg/list-ordered.svg
* assets/vendor/octicons/svg/list-unordered.svg
* assets/vendor/octicons/svg/location.svg
* assets/vendor/octicons/svg/lock.svg
* assets/vendor/octicons/svg/logo-github.svg
* assets/vendor/octicons/svg/mail-read.svg
* assets/vendor/octicons/svg/mail-reply.svg
* assets/vendor/octicons/svg/mail.svg
* assets/vendor/octicons/svg/mark-github.svg
* assets/vendor/octicons/svg/markdown.svg
* assets/vendor/octicons/svg/megaphone.svg
* assets/vendor/octicons/svg/mention.svg
* assets/vendor/octicons/svg/milestone.svg
* assets/vendor/octicons/svg/mirror.svg
* assets/vendor/octicons/svg/mortar-board.svg
* assets/vendor/octicons/svg/mute.svg
* assets/vendor/octicons/svg/no-newline.svg
* assets/vendor/octicons/svg/octoface.svg
* assets/vendor/octicons/svg/organization.svg
* assets/vendor/octicons/svg/package.svg
* assets/vendor/octicons/svg/paintcan.svg
* assets/vendor/octicons/svg/pencil.svg
* assets/vendor/octicons/svg/person.svg
* assets/vendor/octicons/svg/pin.svg
* assets/vendor/octicons/svg/plug.svg
* assets/vendor/octicons/svg/plus.svg
* assets/vendor/octicons/svg/primitive-dot.svg
* assets/vendor/octicons/svg/primitive-square.svg
* assets/vendor/octicons/svg/pulse.svg
* assets/vendor/octicons/svg/question.svg
* assets/vendor/octicons/svg/quote.svg
* assets/vendor/octicons/svg/radio-tower.svg
* assets/vendor/octicons/svg/repo-clone.svg
* assets/vendor/octicons/svg/repo-force-push.svg
* assets/vendor/octicons/svg/repo-forked.svg
* assets/vendor/octicons/svg/repo-pull.svg
* assets/vendor/octicons/svg/repo-push.svg
* assets/vendor/octicons/svg/repo.svg
* assets/vendor/octicons/svg/rocket.svg
* assets/vendor/octicons/svg/rss.svg
* assets/vendor/octicons/svg/ruby.svg
* assets/vendor/octicons/svg/screen-full.svg
* assets/vendor/octicons/svg/screen-normal.svg
* assets/vendor/octicons/svg/search.svg
* assets/vendor/octicons/svg/server.svg
* assets/vendor/octicons/svg/settings.svg
* assets/vendor/octicons/svg/sign-in.svg
* assets/vendor/octicons/svg/sign-out.svg
* assets/vendor/octicons/svg/squirrel.svg
* assets/vendor/octicons/svg/star.svg
* assets/vendor/octicons/svg/stop.svg
* assets/vendor/octicons/svg/sync.svg
* assets/vendor/octicons/svg/tag.svg
* assets/vendor/octicons/svg/telescope.svg
* assets/vendor/octicons/svg/terminal.svg
* assets/vendor/octicons/svg/three-bars.svg
* assets/vendor/octicons/svg/thumbsdown.svg
* assets/vendor/octicons/svg/thumbsup.svg
* assets/vendor/octicons/svg/tools.svg
* assets/vendor/octicons/svg/trashcan.svg
* assets/vendor/octicons/svg/triangle-down.svg
* assets/vendor/octicons/svg/triangle-left.svg
* assets/vendor/octicons/svg/triangle-right.svg
* assets/vendor/octicons/svg/triangle-up.svg
* assets/vendor/octicons/svg/unfold.svg
* assets/vendor/octicons/svg/unmute.svg
* assets/vendor/octicons/svg/versions.svg
* assets/vendor/octicons/svg/watch.svg
* assets/vendor/octicons/svg/x.svg
* assets/vendor/octicons/svg/zap.svg
* assets/vendor/retinajs/.bower.json
* assets/vendor/retinajs/.gitignore
* assets/vendor/retinajs/.travis.yml
* assets/vendor/retinajs/LICENSE
* assets/vendor/retinajs/Makefile
* assets/vendor/retinajs/README.md
* assets/vendor/retinajs/package.json
* assets/vendor/retinajs/src/retina.js
* assets/vendor/retinajs/src/retina.less
* assets/vendor/retinajs/test/fixtures/desired_output.css
* assets/vendor/retinajs/test/fixtures/image.js
* assets/vendor/retinajs/test/fixtures/test.less
* assets/vendor/retinajs/test/fixtures/xml_http_request.js
* assets/vendor/retinajs/test/functional/public/google.png
* assets/vendor/retinajs/test/functional/public/google@1x.png
* assets/vendor/retinajs/test/functional/public/google@2x.png
* assets/vendor/retinajs/test/functional/public/index.html
* assets/vendor/retinajs/test/functional/public/ipad_hero.jpeg
* assets/vendor/retinajs/test/functional/public/ipad_hero@1x.jpeg
* assets/vendor/retinajs/test/functional/public/ipad_hero@2x.jpeg
* assets/vendor/retinajs/test/mocha.opts
* assets/vendor/retinajs/test/retina.test.js
* assets/vendor/retinajs/test/retina_image_path.test.js
* assets/vendor/retinajs/test/retina_less.test.js
* bower.json
* gulpfile.js
* package.json

### Removed files: 

* favicon.ico
* static/css/octicons.eot
* static/css/octicons.svg
* static/css/octicons.ttf
* static/css/octicons.woff
* static/js/jquery.js
* static/js/retina.js

### CODE REVIEW

**Comment by SunghanKim** [comment]
https://public.govdelivery.com/accounts/USFRB/subscriber/edit?preferences=true

**Comment by Shredder121** [comment]
@SunghanKim @technoweenie what is this?

**Comment by technoweenie** [comment]
An automated task would be my guess.

**Comment by Shredder121** [comment]
I take it you removed the comment.
There was spam in a comment on the PR.
Anyway, have a good day!

**Pull request merged**
