### PR TITLE
Fix capitalization for "pull request"

### PR DESCRIPTION
**Pull request by pravipati**
Change "Pull Request" to "pull request" when referring to an instance of a pull request and not Pull Requests as a feature.

### CODE REVIEW

**Comment by brntbeer** [comment]
@pravipati thanks! Just going to bring in some folks in case i lead you astray

@bernars / @gjtorikian I think that's what I've heard from yall and it's The Right Way™. Thoughts?

**Comment by gjtorikian** [comment]
/cc @github/docs-platform 

But yes, that's right!

**Comment by Youthpresident** [comment]
right

**Comment by pravipati** [comment]
@gjtorikian @github/docs-platform is this good to 🚢 ?

**Comment by gjtorikian** [comment]
:shipit:

**Pull request merged**
