### PR TITLE
added the http command

### PR DESCRIPTION
**Pull request by AnnAddicks**
I was following this tutorial today and ngrok + the port causes the following error:  "Unrecognized command: 4567".

### CODE REVIEW

**Comment by gjtorikian** [comment]
When I try this command, I get:

```
$ ngrok http 4567
> You may only specify one port to tunnel to on the command line, got 2: [http 4567]
```

I've actually never seen the `http` argument before. What does it do? Here's the `-h` information:

```
Usage: ngrok [OPTIONS] <local port or address>
Options:
  -authtoken="": Authentication token for identifying an ngrok.com account
  -config="": Path to ngrok configuration file. (default: $HOME/.ngrok)
  -hostname="": Request a custom hostname from the ngrok server. (HTTP only) (requires CNAME of your DNS)
  -httpauth="": username:password HTTP basic auth creds protecting the public tunnel endpoint
  -log="none": Write log messages to this file. 'stdout' and 'none' have special meanings
  -proto="http+https": The protocol of the traffic over the tunnel {'http', 'https', 'tcp'} (default: 'http+https')
  -subdomain="": Request a custom subdomain from the ngrok server. (HTTP only)

Examples:
	ngrok 80
	ngrok -subdomain=example 8080
	ngrok -proto=tcp 22
	ngrok -hostname="example.com" -httpauth="user:password" 10.0.0.1


Advanced usage: ngrok [OPTIONS] <command> [command args] [...]
Commands:
	ngrok start [tunnel] [...]    Start tunnels by name from config file
	ngrok help                    Print help
	ngrok version                 Print ngrok version

Examples:
	ngrok start www api blog pubsub
	ngrok -log=stdout -config=ngrok.yml start ssh
	ngrok version
```

I am on ngrok 1.6.

**Comment by AnnAddicks** [comment]
I just downloaded ngrok today for the tutorial -  ngrok version 2.0.17
I guess they added the tunnel command as a requirement in 2.

**Comment by gjtorikian** [comment]
You're completely right! I upgraded and had the same issue.

Thanks so much for your PR. Because it was made against the `minor-changes` branch, instead of `master`, I went ahead and [cherry-picked the commit](https://github.com/github/developer.github.com/commit/ff93c8f472250efb443ed322b6421f816c11153f) so that you retain contribution credit. Thanks again!

**Comment by AnnAddicks** [comment]
Thanks!  Sorry about the branch, I had 30 minutes to work the tutorial and didn't check any docs to see which branch you guys preferred and it was a pretty minor change :D

**Comment by gjtorikian** [comment]
No worries, we appreciate the change.

**Comment by sigmavirus24** [comment]
:cake:

**Pull request closed without merging**
