### PR TITLE
Serialize the `search-index.json` alphabetically

### PR DESCRIPTION
**Pull request by Shredder121**
This ensures that after deployment the `search-index.json` is in a consistent state so the order can be reproduced build after build.
Inspired by https://github.com/github/developer.github.com/commit/821c7fbbd08ffd8706d1a60370a50cb21f29af46#diff-3e285797a87ae049427e9c86def110cb

### CODE REVIEW

**Comment by Shredder121** [comment]
Please do comment about these issues:

-----

:bug: Using `clean_for_json` with this approach escapes backslashes too much.
:speech_balloon: This is not such a big issue, since ` \\\"` is still a working `\` `"`

-----

:bulb: We could leverage `JSON.generate()` instead of `JSON.pretty_generate()` in production builds.
 :speech_balloon: This means that the json is also minimized when served.

-------

I hope to hear feedback.

**Comment by Shredder121** [comment]
Here is a [Gist with the resulting json][].
The diff between the revisions is the most interesting.

[gist with the resulting json]: https://gist.github.com/Shredder121/fc380b5bd84f1bc05b2a

**Comment by gjtorikian** [comment]
> This means that the json is also minimized when served.

You can use `ENV['RACK_ENV' ]== "production"` to determine if we are in production. I think it makes sense to minify.

Did the time to generate the site change with this change? Can you show the generation time for `master` and this branch to compare?

**Comment by Shredder121** [comment]
> Can you show the generation time for master and this branch to compare?

Yes, with `rm -r output/` first? or also `tmp/`?
The entire site?

**Comment by Shredder121** [comment]
Did it with `rm -r output/` in between runs.

Seems to be negligible.

status quo:

```bash
$ time bundle exec nanoc compile > statusquo

real    0m24.009s
user    0m0.000s
sys     0m0.000s
```

with output:

```
Loading site… done
Compiling site…
      create  [0.02s]  output/404.html
      create  [0.11s]  output/changes/2012-09-05-watcher-api/index.html
...
      create  [0.03s]  output/v3/orgs/migrations/index.html
      create  [0.36s]  output/search/search-index.json

Site compiled in 23.00s.
```

new:

```bash
$ bundle exec nanoc compile > newbranch
real    0m23.671s
user    0m0.000s
sys     0m0.000s
```

with output:

```
Loading site… done
Compiling site…
      create  [0.03s]  output/404.html
      create  [0.11s]  output/changes/2012-09-05-watcher-api/index.html
...
      create  [0.03s]  output/v3/orgs/migrations/index.html
      create  [0.37s]  output/search/search-index.json

Site compiled in 22.67s.
```

**Comment by gjtorikian** [comment]
If you add the minification of the JSON in production I think this would be good to merge.

**Comment by Shredder121** [comment]
Done :zap:

**Comment by gjtorikian** [comment]
Cool. Thank you!

**Comment by Shredder121** [comment]
Nice. Thank you!

**Pull request merged**
