### PR TITLE
Added information regarding auth 404 error

### PR DESCRIPTION
**Pull request by davidcorbin**
Added information about a common error when exchanging Github code for access_token. http://stackoverflow.com/search?q=https%3A%2F%2Fgithub.com%2Flogin%2Foauth%2Faccess_token

### CODE REVIEW

**Comment by mikemcquaid** [comment]
CCing by coworkers in @github/platform and @github/docs-platform for thoughts on this documentation change.

**Comment by mikemcquaid** [comment]
Hi @daconex, thanks for the pull request :sparkles:. My only concern about this is that if we go down this path we may end up with lots of people submitting documentation additions for specific errors. What do you think? Did you find this behaviour really unexpected or surprising? Thanks again :zap:!

**Comment by daconex** [comment]
@mikemcquaid thanks for the reply! I see how including all error cases would be way too much. It may be a good idea to include some kind of notice about HTTP statuses such as 404 Not Found that are sent even when the url being requested is correct. 

An even better solution would be to, instead of returning 404, return 200 and send JSON/XML data explaining that the client application couldn't be authorized. But that requires way more work than a documentation change :laughing:.

**Comment by mikemcquaid** [comment]
> It may be a good idea to include some kind of notice about HTTP statuses such as 404 Not Found that are sent even when the url being requested is correct.

Yeh, we do cover that elsewhere in the documentation:
https://github.com/github/developer.github.com/blob/master/content/v3/troubleshooting.md#why-am-i-getting-a-404-error-on-a-repository-that-exists

Do you think it's worth extending that section to clarify this point?

**Comment by daconex** [comment]
I think it is worth extending the section. Maybe put the link in as well!

**Comment by mikemcquaid** [comment]
@daconex Could you give a go at extending the linked section (and removing the existing changes) so that it would have addressed your question? Thanks!

**Comment by mikemcquaid** [comment]
@daconex Sorry, I wasn't clear: could we make the text in the troubleshooting page more generic so that it helps explain this issue and leave the OAuth page-as? Thanks!

**Comment by daconex** [comment]
After looking more in depth at the documentation, I realize that it's clear enough the way it is and doesn't need to show the error messages I proposed. @mikemcquaid thank you!

**Comment by mikemcquaid** [comment]
@daconex Thanks for the kind words and your pull request. You rock!

**Pull request closed without merging**
