### PR TITLE
Fix typo on for API fork endpoint

### PR DESCRIPTION
**Pull request by davidxia**

### CODE REVIEW

**Comment by davidxia** [comment]
@pengwynn

**Comment by pengwynn** [comment]
@davidxia I just double-checked the API source and the docs are correct. As the blog post explains, the deprecated query param is `?org=` but if you pass it in the JSON payload it's `organization`. Did you find results to the contrary? If so, [get in touch][] with your `curl -v` output (masking any tokens or passwords) and we can investigate.

[get in touch]: http://git.io/vmk9z

**Comment by davidxia** [comment]
Here's a request as specified by the current docs using "organization":

```
curl -X POST -u <personal access token>:x-oauth-basic 'https://api.github.com/repos/kennethreitz/requests/forks' -d '{"organization":"davidxia"}' -v
* Hostname was NOT found in DNS cache
*   Trying 192.30.252.139...
* Connected to api.github.com (192.30.252.139) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
* Server certificate: *.github.com
* Server certificate: DigiCert SHA2 High Assurance Server CA
* Server certificate: DigiCert High Assurance EV Root CA
* Server auth using Basic with user '<personal access token>'
> POST /repos/kennethreitz/requests/forks HTTP/1.1
> Authorization: Basic XXX
> User-Agent: curl/7.37.1
> Host: api.github.com
> Accept: */*
> Content-Length: 27
> Content-Type: application/x-www-form-urlencoded
>
* upload completely sent off: 27 out of 27 bytes
< HTTP/1.1 422 Unprocessable Entity
* Server GitHub.com is not blacklisted
< Server: GitHub.com
< Date: Mon, 13 Jul 2015 20:04:14 GMT
< Content-Type: application/json; charset=utf-8
< Content-Length: 234
< Status: 422 Unprocessable Entity
< X-RateLimit-Limit: 5000
< X-RateLimit-Remaining: 4996
< X-RateLimit-Reset: 1436821432
< X-OAuth-Scopes: gist, repo, user
< X-Accepted-OAuth-Scopes: repo
< X-GitHub-Media-Type: github.v3
< X-XSS-Protection: 1; mode=block
< X-Frame-Options: deny
< Content-Security-Policy: default-src 'none'
< Access-Control-Allow-Credentials: true
< Access-Control-Expose-Headers: ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval
< Access-Control-Allow-Origin: *
< X-GitHub-Request-Id: 4AC983A7:61C0:6F53F9D:55A419BE
< Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
< X-Content-Type-Options: nosniff
<
{
  "message": "Validation Failed",
  "errors": [
    {
      "resource": "Fork",
      "code": "invalid",
      "field": "organization"
    }
  ],
  "documentation_url": "https://developer.github.com/v3/repos/forks/#create-a-fork"
}
* Connection #0 to host api.github.com left intact
```

Here's a request after changing "organization" to "org":

```
curl -X POST -u <personal access token>:x-oauth-basic 'https://api.github.com/repos/kennethreitz/requests/forks' -d '{"org":"davidxia"}' -v

* Hostname was NOT found in DNS cache
*   Trying 192.30.252.139...
* Connected to api.github.com (192.30.252.139) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
* Server certificate: *.github.com
* Server certificate: DigiCert SHA2 High Assurance Server CA
* Server certificate: DigiCert High Assurance EV Root CA
* Server auth using Basic with user '<personal access token>'
> POST /repos/kennethreitz/requests/forks HTTP/1.1
> Authorization: Basic XXX
> User-Agent: curl/7.37.1
> Host: api.github.com
> Accept: */*
> Content-Length: 18
> Content-Type: application/x-www-form-urlencoded
>
* upload completely sent off: 18 out of 18 bytes
< HTTP/1.1 202 Accepted
* Server GitHub.com is not blacklisted
< Server: GitHub.com
< Date: Mon, 13 Jul 2015 20:04:10 GMT
< Content-Type: application/json; charset=utf-8
< Content-Length: 15672
< Status: 202 Accepted
< X-RateLimit-Limit: 5000
< X-RateLimit-Remaining: 4997
< X-RateLimit-Reset: 1436821432
< X-OAuth-Scopes: gist, repo, user
< X-Accepted-OAuth-Scopes:
< X-GitHub-Media-Type: github.v3
< X-XSS-Protection: 1; mode=block
< X-Frame-Options: deny
< Content-Security-Policy: default-src 'none'
< Access-Control-Allow-Credentials: true
< Access-Control-Expose-Headers: ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval
< Access-Control-Allow-Origin: *
< X-GitHub-Request-Id: 4AC983A7:61BF:61141AA:55A419BA
< Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
< X-Content-Type-Options: nosniff
<
{
  "id": 38905236,
  "name": "requests",
  "full_name": "davidxia/requests",
  "owner": {
    "login": "davidxia",
    "id": 480621,
    "avatar_url": "https://avatars.githubusercontent.com/u/480621?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/davidxia",
    "html_url": "https://github.com/davidxia",
    "followers_url": "https://api.github.com/users/davidxia/followers",
    "following_url": "https://api.github.com/users/davidxia/following{/other_user}",
    "gists_url": "https://api.github.com/users/davidxia/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/davidxia/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/davidxia/subscriptions",
    "organizations_url": "https://api.github.com/users/davidxia/orgs",
    "repos_url": "https://api.github.com/users/davidxia/repos",
    "events_url": "https://api.github.com/users/davidxia/events{/privacy}",
    "received_events_url": "https://api.github.com/users/davidxia/received_events",
    "type": "User",
    "site_admin": false
  },
  "private": false,
  "html_url": "https://github.com/davidxia/requests",
  "description": "Python HTTP Requests for Humans™.",
  "fork": true,
  "url": "https://api.github.com/repos/davidxia/requests",
  "forks_url": "https://api.github.com/repos/davidxia/requests/forks",
  "keys_url": "https://api.github.com/repos/davidxia/requests/keys{/key_id}",
  "collaborators_url": "https://api.github.com/repos/davidxia/requests/collaborators{/collaborator}",
  "teams_url": "https://api.github.com/repos/davidxia/requests/teams",
  "hooks_url": "https://api.github.com/repos/davidxia/requests/hooks",
  "issue_events_url": "https://api.github.com/repos/davidxia/requests/issues/events{/number}",
  "events_url": "https://api.github.com/repos/davidxia/requests/events",
  "assignees_url": "https://api.github.com/repos/davidxia/requests/assignees{/user}",
  "branches_url": "https://api.github.com/repos/davidxia/requests/branches{/branch}",
  "tags_url": "https://api.github.com/repos/davidxia/requests/tags",
  "blobs_url": "https://api.github.com/repos/davidxia/requests/git/blobs{/sha}",
  "git_tags_url": "https://api.github.com/repos/davidxia/requests/git/tags{/sha}",
  "git_refs_url": "https://api.github.com/repos/davidxia/requests/git/refs{/sha}",
  "trees_url": "https://api.github.com/repos/davidxia/requests/git/trees{/sha}",
  "statuses_url": "https://api.github.com/repos/davidxia/requests/statuses/{sha}",
  "languages_url": "https://api.github.com/repos/davidxia/requests/languages",
  "stargazers_url": "https://api.github.com/repos/davidxia/requests/stargazers",
  "contributors_url": "https://api.github.com/repos/davidxia/requests/contributors",
  "subscribers_url": "https://api.github.com/repos/davidxia/requests/subscribers",
  "subscription_url": "https://api.github.com/repos/davidxia/requests/subscription",
  "commits_url": "https://api.github.com/repos/davidxia/requests/commits{/sha}",
  "git_commits_url": "https://api.github.com/repos/davidxia/requests/git/commits{/sha}",
  "comments_url": "https://api.github.com/repos/davidxia/requests/comments{/number}",
  "issue_comment_url": "https://api.github.com/repos/davidxia/requests/issues/comments{/number}",
  "contents_url": "https://api.github.com/repos/davidxia/requests/contents/{+path}",
  "compare_url": "https://api.github.com/repos/davidxia/requests/compare/{base}...{head}",
  "merges_url": "https://api.github.com/repos/davidxia/requests/merges",
  "archive_url": "https://api.github.com/repos/davidxia/requests/{archive_format}{/ref}",
  "downloads_url": "https://api.github.com/repos/davidxia/requests/downloads",
  "issues_url": "https://api.github.com/repos/davidxia/requests/issues{/number}",
  "pulls_url": "https://api.github.com/repos/davidxia/requests/pulls{/number}",
  "milestones_url": "https://api.github.com/repos/davidxia/requests/milestones{/number}",
  "notifications_url": "https://api.github.com/repos/davidxia/requests/notifications{?since,all,participating}",
  "labels_url": "https://api.github.com/repos/davidxia/requests/labels{/name}",
  "releases_url": "https://api.github.com/repos/davidxia/requests/releases{/id}",
  "created_at": "2015-07-10T22:42:42Z",
  "updated_at": "2015-07-10T22:42:44Z",
  "pushed_at": "2015-07-10T08:14:55Z",
  "git_url": "git://github.com/davidxia/requests.git",
  "ssh_url": "git@github.com:davidxia/requests.git",
  "clone_url": "https://github.com/davidxia/requests.git",
  "svn_url": "https://github.com/davidxia/requests",
  "homepage": "python-requests.org",
  "size": 13487,
  "stargazers_count": 0,
  "watchers_count": 0,
  "language": "Python",
  "has_issues": false,
  "has_downloads": true,
  "has_wiki": true,
  "has_pages": false,
  "forks_count": 0,
  "mirror_url": null,
  "open_issues_count": 0,
  "forks": 0,
  "open_issues": 0,
  "watchers": 0,
  "default_branch": "master",
  "permissions": {
    "admin": true,
    "push": true,
    "pull": true
  },
  "parent": {
    "id": 1362490,
    "name": "requests",
    "full_name": "kennethreitz/requests",
    "owner": {
      "login": "kennethreitz",
      "id": 119893,
      "avatar_url": "https://avatars.githubusercontent.com/u/119893?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kennethreitz",
      "html_url": "https://github.com/kennethreitz",
      "followers_url": "https://api.github.com/users/kennethreitz/followers",
      "following_url": "https://api.github.com/users/kennethreitz/following{/other_user}",
      "gists_url": "https://api.github.com/users/kennethreitz/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/kennethreitz/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/kennethreitz/subscriptions",
      "organizations_url": "https://api.github.com/users/kennethreitz/orgs",
      "repos_url": "https://api.github.com/users/kennethreitz/repos",
      "events_url": "https://api.github.com/users/kennethreitz/events{/privacy}",
      "received_events_url": "https://api.github.com/users/kennethreitz/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/kennethreitz/requests",
    "description": "Python HTTP Requests for Humans™.",
    "fork": false,
    "url": "https://api.github.com/repos/kennethreitz/requests",
    "forks_url": "https://api.github.com/repos/kennethreitz/requests/forks",
    "keys_url": "https://api.github.com/repos/kennethreitz/requests/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/kennethreitz/requests/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/kennethreitz/requests/teams",
    "hooks_url": "https://api.github.com/repos/kennethreitz/requests/hooks",
    "issue_events_url": "https://api.github.com/repos/kennethreitz/requests/issues/events{/number}",
    "events_url": "https://api.github.com/repos/kennethreitz/requests/events",
    "assignees_url": "https://api.github.com/repos/kennethreitz/requests/assignees{/user}",
    "branches_url": "https://api.github.com/repos/kennethreitz/requests/branches{/branch}",
    "tags_url": "https://api.github.com/repos/kennethreitz/requests/tags",
    "blobs_url": "https://api.github.com/repos/kennethreitz/requests/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/kennethreitz/requests/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/kennethreitz/requests/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/kennethreitz/requests/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/kennethreitz/requests/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/kennethreitz/requests/languages",
    "stargazers_url": "https://api.github.com/repos/kennethreitz/requests/stargazers",
    "contributors_url": "https://api.github.com/repos/kennethreitz/requests/contributors",
    "subscribers_url": "https://api.github.com/repos/kennethreitz/requests/subscribers",
    "subscription_url": "https://api.github.com/repos/kennethreitz/requests/subscription",
    "commits_url": "https://api.github.com/repos/kennethreitz/requests/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/kennethreitz/requests/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/kennethreitz/requests/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/kennethreitz/requests/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/kennethreitz/requests/contents/{+path}",
    "compare_url": "https://api.github.com/repos/kennethreitz/requests/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/kennethreitz/requests/merges",
    "archive_url": "https://api.github.com/repos/kennethreitz/requests/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/kennethreitz/requests/downloads",
    "issues_url": "https://api.github.com/repos/kennethreitz/requests/issues{/number}",
    "pulls_url": "https://api.github.com/repos/kennethreitz/requests/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/kennethreitz/requests/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/kennethreitz/requests/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/kennethreitz/requests/labels{/name}",
    "releases_url": "https://api.github.com/repos/kennethreitz/requests/releases{/id}",
    "created_at": "2011-02-13T18:38:17Z",
    "updated_at": "2015-07-13T18:45:45Z",
    "pushed_at": "2015-07-13T13:07:57Z",
    "git_url": "git://github.com/kennethreitz/requests.git",
    "ssh_url": "git@github.com:kennethreitz/requests.git",
    "clone_url": "https://github.com/kennethreitz/requests.git",
    "svn_url": "https://github.com/kennethreitz/requests",
    "homepage": "python-requests.org",
    "size": 13487,
    "stargazers_count": 14495,
    "watchers_count": 14495,
    "language": "Python",
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 2418,
    "mirror_url": null,
    "open_issues_count": 72,
    "forks": 2418,
    "open_issues": 72,
    "watchers": 14495,
    "default_branch": "master"
  },
  "source": {
    "id": 1362490,
    "name": "requests",
    "full_name": "kennethreitz/requests",
    "owner": {
      "login": "kennethreitz",
      "id": 119893,
      "avatar_url": "https://avatars.githubusercontent.com/u/119893?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kennethreitz",
      "html_url": "https://github.com/kennethreitz",
      "followers_url": "https://api.github.com/users/kennethreitz/followers",
      "following_url": "https://api.github.com/users/kennethreitz/following{/other_user}",
      "gists_url": "https://api.github.com/users/kennethreitz/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/kennethreitz/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/kennethreitz/subscriptions",
      "organizations_url": "https://api.github.com/users/kennethreitz/orgs",
      "repos_url": "https://api.github.com/users/kennethreitz/repos",
      "events_url": "https://api.github.com/users/kennethreitz/events{/privacy}",
      "received_events_url": "https://api.github.com/users/kennethreitz/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/kennethreitz/requests",
    "description": "Python HTTP Requests for Humans™.",
    "fork": false,
    "url": "https://api.github.com/repos/kennethreitz/requests",
    "forks_url": "https://api.github.com/repos/kennethreitz/requests/forks",
    "keys_url": "https://api.github.com/repos/kennethreitz/requests/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/kennethreitz/requests/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/kennethreitz/requests/teams",
    "hooks_url": "https://api.github.com/repos/kennethreitz/requests/hooks",
    "issue_events_url": "https://api.github.com/repos/kennethreitz/requests/issues/events{/number}",
    "events_url": "https://api.github.com/repos/kennethreitz/requests/events",
    "assignees_url": "https://api.github.com/repos/kennethreitz/requests/assignees{/user}",
    "branches_url": "https://api.github.com/repos/kennethreitz/requests/branches{/branch}",
    "tags_url": "https://api.github.com/repos/kennethreitz/requests/tags",
    "blobs_url": "https://api.github.com/repos/kennethreitz/requests/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/kennethreitz/requests/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/kennethreitz/requests/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/kennethreitz/requests/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/kennethreitz/requests/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/kennethreitz/requests/languages",
    "stargazers_url": "https://api.github.com/repos/kennethreitz/requests/stargazers",
    "contributors_url": "https://api.github.com/repos/kennethreitz/requests/contributors",
    "subscribers_url": "https://api.github.com/repos/kennethreitz/requests/subscribers",
    "subscription_url": "https://api.github.com/repos/kennethreitz/requests/subscription",
    "commits_url": "https://api.github.com/repos/kennethreitz/requests/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/kennethreitz/requests/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/kennethreitz/requests/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/kennethreitz/requests/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/kennethreitz/requests/contents/{+path}",
    "compare_url": "https://api.github.com/repos/kennethreitz/requests/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/kennethreitz/requests/merges",
    "archive_url": "https://api.github.com/repos/kennethreitz/requests/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/kennethreitz/requests/downloads",
    "issues_url": "https://api.github.com/repos/kennethreitz/requests/issues{/number}",
    "pulls_url": "https://api.github.com/repos/kennethreitz/requests/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/kennethreitz/requests/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/kennethreitz/requests/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/kennethreitz/requests/labels{/name}",
    "releases_url": "https://api.github.com/repos/kennethreitz/requests/releases{/id}",
    "created_at": "2011-02-13T18:38:17Z",
    "updated_at": "2015-07-13T18:45:45Z",
    "pushed_at": "2015-07-13T13:07:57Z",
    "git_url": "git://github.com/kennethreitz/requests.git",
    "ssh_url": "git@github.com:kennethreitz/requests.git",
    "clone_url": "https://github.com/kennethreitz/requests.git",
    "svn_url": "https://github.com/kennethreitz/requests",
    "homepage": "python-requests.org",
    "size": 13487,
    "stargazers_count": 14495,
    "watchers_count": 14495,
    "language": "Python",
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 2418,
    "mirror_url": null,
    "open_issues_count": 72,
    "forks": 2418,
    "open_issues": 72,
    "watchers": 14495,
    "default_branch": "master"
  },
  "network_count": 2418,
  "subscribers_count": 0
}
* Connection #0 to host api.github.com left intact
```

**Comment by pengwynn** [comment]
Ah, I see the issue. Since `davidxia` is a human, not an organization, it's rightly returning `422`, but we don't do a good job of explaining why in that error message. I'll open an issue to fix that.

It succeeds in your second example because `org` is ignored when passed in the POST body. Note the fork was created under your personal account. Does that help?

**Comment by davidxia** [comment]
@pengwynn Ah I see. I don't need the "organization" at all if I'm a human. Maybe the [docs here][1] can be a little clearer about this. I thought the organization field was needed all the time. Now I notice there's no "Required."

  [1]: https://developer.github.com/v3/repos/forks/#create-a-fork

**Comment by davidxia** [comment]
Maybe something like https://github.com/github/developer.github.com/pull/819

**Pull request closed without merging**
