### PR TITLE
Assignees rename fields

### PR DESCRIPTION
**Pull request by Shredder121**
I saw that the original user was not in the `assignees` list, and that the users in the `assignees` list weren't consistent.
This updates (merges) the `USER` with itself, updating all fields with the block. (if anyone knows of a nicer way, let me know)
This makes the data a little more realistic.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
@gjtorikian Any thoughts here?

**Comment by gjtorikian** [comment]
It's definitely clever, but I think we should just opt for explicitness. @Shredder121, would you mind simply copying the `USER` constant and naming it `HUBOT`, and just manually replacing the words with `hubot`? That would allow us to use these other users in the future. Thank you!

**Comment by Shredder121** [comment]
Should I also use the values from https://api.github.com/users/hubot?

**Comment by Shredder121** [comment]
And what about `other_user`?

**Comment by HubleGiter** [comment]
Sounds great I am glad to see some resolve to this issue.

**Comment by gjtorikian** [comment]
@Shredder121 Nah, you can keep the `hubot` stuff much simpler, no need to actually add all the repositories and what not. Same with `other_user`, just copy the same stuff in `USER` and replace the username.

**Comment by Shredder121** [comment]
There, how's that?

**Comment by Shredder121** [comment]
What happened to Travis?
https://travis-ci.org/github/developer.github.com

**Comment by MikeMcQuaid** [comment]
@Shredder121 not sure but reactivated it now.

**Comment by gjtorikian** [comment]
Beautiful. Thanks as always @Shredder121!

**Comment by Shredder121** [comment]
Haha, no problem as always! :+1:

**Pull request merged**
