### PR TITLE
Add missing repository.deployments_url field

### PR DESCRIPTION
**Pull request by Shredder121**
I could only quickly get my hands on a handful of events, but I assume that each payload's elements are identical.

### CODE REVIEW

**Comment by tarebyte** [comment]
Hey @Shredder121, thanks for the pull request!

I'm taking some time this week to update all of the webhook payloads so that they are all up to date.

I'm going to close this, but we really appreciate you taking the time to make the developer site more accurate for users.

I'll ping you in this issue to let you know when those changes go out.

**Comment by Shredder121** [comment]
That's cool with me. and of course I do my part.
Can I make a request?
Could you make all the webhook payloads (except for `member` :wink:) in an Organization context?
That way, all the payloads will be complete.

**Comment by Shredder121** [comment]
Is there any news yet on when this can be expected?
I'd really like full payload files, and exporting them on my own every now and then is very tedious.
Moreover, usually when I export a 'new' one, nothing has changed.
I'd rather have this repository host them.

**Comment by SKY51717** [comment]
****

**Comment by MikeMcQuaid** [comment]
CC @tarebyte for thoughts on this.

**Comment by Shredder121** [comment]
@tarebyte a :moneybag: for your :thought_balloon:?

**Comment by tarebyte** [comment]
Sorry for the delay folks, I meant to get around to updating all of the payloads but just ran out of time.

@Shredder121 if you open up another PR I'll merge it.

Thanks!

**Comment by Shredder121** [comment]
With updated paloads? Or just the missing `repository.deploymentsUrl` field?
I think now we're also missing [multiple assignees][multiple assignees]?
(would make for a good payload subject if you ask me)

An aside note, if someone will eventually update it, I am fine with waiting.


[multiple assignees]: http://developer.github.com/changes/2016-07-12-ending-multiple-assignees-preview-period/

**Comment by tarebyte** [comment]
@Shredder121 yeah I'm fine with accepting any kind of updated payload.

**Pull request closed without merging**
