### PR TITLE
Revert "Modified content/webhooks/index.md"

### PR DESCRIPTION
**Pull request by Shredder121**
For some reason Hubot doesn't like me.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Going back and foward and back and foward, lol.

**Comment by Shredder121** [comment]
In the end only one will win.
I hope it's not a capable, fully automated bot though. :/
But I'll persevere.

**Comment by Veroniqur** [comment]
Et selin vous lequel serable vainceur:)

**Comment by Shredder121** [comment]
Could you stop that?

**Comment by gjtorikian** [comment]
Sorry about that! We've rejiggered the sync in https://github.com/github/developer.github.com/pull/981.

**Comment by SPikeVanz** [comment]
#

**Pull request closed without merging**
