### PR TITLE
No field is required when updating an issue label

### PR DESCRIPTION
**Pull request by pdalpra**

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Thanks for the PR. This does seem odd, though. What happens if you specify neither attribute? CC @izuzak and @gjtorikian for thoughts on ths.

**Comment by pdalpra** [comment]
If you pass an empty request body, the response is a 400 (the error message being `Problems parsing JSON`).
If the body is a empty JSON object, this is simply a noop, the label stays unchanged and its current configuration is returned (eg. same response as https://developer.github.com/v3/issues/labels/#get-a-single-label)

**Comment by mikemcquaid** [comment]
Did you try the case where only one value is specified? Thanks for the pull regardless but I think the case you've described is somewhere we need to change the code rather than documentation.

**Comment by pdalpra** [comment]
I did, and it only updates the attribute specified in the payload.
However, I am no REST API expert but that behaviour is IMHO more in line with the classical usage of the `PATCH` HTTP verb, eg. partial modification of a resource.

**Comment by izuzak** [comment]
I think this is fine, similar to how the endpoint for modifying an issue is documented:

https://developer.github.com/v3/issues/#edit-an-issue

There are no required parameters.

**Comment by gjtorikian** [comment]
I find the current behavior odd and would prefer a change in the code. I imagine the original intent was that either the name or the color should be required, which is more inline with how the UI behaves.

**Comment by MikeMcQuaid** [comment]
Thanks for the pull request @pdalpra!

**Pull request merged**
