### PR TITLE
Updated "push" event payload to match

### PR DESCRIPTION
**Pull request by julianlam**
- Fixed ordering of keys (just for organisation, really)
- Added `added`, `modified`, `removed`, and `committer` keys
- Fixed incorrect key `sha`, should be `id`

### CODE REVIEW

**Comment by julianlam** [comment]
For reference, here is the payload received by my webhook using v3 of the GitHub API:

``` json
[ { id: '22f73a8f68762ed404582f0dda2455a3d1bedfee',
    distinct: true,
    message: 'fixes #4463',
    timestamp: '2016-03-25T13:24:40-04:00',
    url: 'https://github.com/NodeBB/NodeBB/commit/22f73a8f68762ed404582f0dda2455a3d1bedfee',
    author: 
     { name: 'Julian Lam',
       email: 'julian@nodebb.org',
       username: 'julianlam' },
    committer: 
     { name: 'Julian Lam',
       email: 'julian@nodebb.org',
       username: 'julianlam' },
    added: 
     [ 'public/src/admin/manage/category-analytics.js',
       'src/views/admin/manage/category-analytics.tpl' ],
    removed: [],
    modified: 
     [ 'public/src/admin/manage/category.js',
       'src/controllers/admin/categories.js',
       'src/routes/admin.js',
       'src/views/admin/manage/category.tpl',
       'src/views/admin/partials/categories/category-rows.tpl' ] } ]
```

**Comment by davidcelis** [comment]
This looks good, @julianlam. Thanks so much for the fix!

**Comment by davidcelis** [comment]
Hey, sorry @julianlam. After merging, I noticed that the section you've updated is for Push events in the activity timeline. These actually _do_ have payloads that differ from webhook events. It's unfortunately confusing, but if you check out the [current documentation on this PushEvent](https://developer.github.com/v3/activity/events/types/#pushevent), you'll see a notice at the top of the section that notes the two payloads are different.

Below the activity timeline payload example, there's an [example of what the webhook event payload looks like](https://developer.github.com/v3/activity/events/types/#webhook-payload-example-15). There you;ll see that the extra fields you mention in this Pull Request are present. Sorry again about the confusion!

**Comment by julianlam** [comment]
Ah, I see. Sorry about the mistake! Though I feel reconciling the differences between the two for the next version would be prudent :smile:

**Pull request merged**
