### PR TITLE
Modified content/webhooks/index.md

### PR DESCRIPTION
**Pull request by hubot**

### CODE REVIEW

**Comment by Shredder121** [comment]
@mikemcquaid Why was this reverted again?

**Comment by bswinnerton** [comment]
Sorry about that @Shredder121! I've reverted the changes of this PR in f687368 and have reprimanded Hubot appropriately.

**Comment by Shredder121** [comment]
Ah, thank you.
Anyway, very strange.

**Comment by Shredder121** [comment]
It's almost as if Hubot doesn't like me :wink:

**Comment by Veroniqur** [comment]
Can you help me for understanding who gona help me I' writing few e-mail and no one did the research about my information anyway nobody let me believe is gona look to have care about. 

Me little me can realize persons put intervention... Stop our no personn . Only think we ask me it's for payment ... Incroyable 

Thank you

**Pull request merged**
